//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace censa
{
    using System;
    using System.Collections.Generic;
    
    public partial class Incidencia
    {
        public int id { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<System.TimeSpan> horaE { get; set; }
        public Nullable<System.TimeSpan> horaS { get; set; }
        public Nullable<int> usuario { get; set; }
        public Nullable<int> tipoIncidencia { get; set; }
        public Nullable<int> tipoJustificacion { get; set; }
        public string observaciones { get; set; }
        public Nullable<bool> justificado { get; set; }
    
        public virtual TipoIncidencia TipoIncidencia1 { get; set; }
        public virtual TipoJustificacion TipoJustificacion1 { get; set; }
    }
}
